const movies = [
  {
    id: '1',
    title: 'Oceans 8',
    category: 'Comedy',
    likes: 4,
    dislikes: 1,
    img: 'https://fr.web.img3.acsta.net/pictures/18/05/14/12/19/5676009.jpg',
  },
  {
    id: '2',
    title: 'Midnight Sun',
    category: 'Comedy',
    likes: 2,
    dislikes: 0,
    img: 'https://images-na.ssl-images-amazon.com/images/I/81Czi+5ArRL.jpg',
  },
  {
    id: '3',
    title: 'Les indestructibles 2',
    category: 'Animation',
    likes: 3,
    dislikes: 1,
    img: 'https://fr.web.img6.acsta.net/pictures/18/04/13/15/09/0323902.jpg',
  },
  {
    id: '4',
    title: 'Sans un bruit',
    category: 'Thriller',
    likes: 6,
    dislikes: 6,
    img: 'https://fr.web.img5.acsta.net/pictures/21/05/06/15/58/0640312.jpg',
  },
  {
    id: '5',
    title: 'Creed II',
    category: 'Drame',
    likes: 16,
    dislikes: 2,
    img: 'https://fr.web.img5.acsta.net/pictures/18/11/27/14/25/1451897.jpg',
  },
  {
    id: '6',
    title: 'Pulp Fiction',
    category: 'Thriller',
    likes: 11,
    dislikes: 3,
    img: 'https://image.posterlounge.fr/images/l/1895909.jpg',
  },
  {
    id: '7',
    title: 'Pulp Fiction',
    category: 'Thriller',
    likes: 12333,
    dislikes: 32,
    img: 'https://image.posterlounge.fr/images/l/1895909.jpg',
  },
  {
    id: '8',
    title: 'Seven',
    category: 'Thriller',
    likes: 2,
    dislikes: 1,
    img: 'https://fr.web.img2.acsta.net/medias/nmedia/18/35/91/33/19255605.jpg',
  },
  {
    id: '9',
    title: 'Inception',
    category: 'Thriller',
    likes: 2,
    dislikes: 1,
    img: 'https://www.telerama.fr/sites/tr_master/files/4b88fb8f-a1f8-4432-a222-17c30c201e6d_2.jpg',
  },
  {
    id: '10',
    title: 'Gone Girl',
    category: 'Thriller',
    likes: 22,
    dislikes: 12,
    img: 'http://addict-culture.com/wp-content/uploads/2014/10/gone-girl-poster.jpg',
  },
];

export default movies;
